---
id: 52
name: "Denys"
phoneNumber: "+380973999060"
lastName: "Ohorodnik"
address:
  id: null
  street: "Nebesnoi Sotni ,4B"
  city: "Chernivtsi"
  zipCode: 58000
sex: "male"
email: "den.ohorodnik@gmail.com"
dateOfBirth: "2010-10-10"
jobs:
- id: null
  companyName: "SoftServe"
  startDate: "2010-02-10"
  endDate: "2012-02-10"
  position: "junior"
